In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data =pd.read_excel("Airbnb_Open_Data.xlsx")

In [3]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,2019-05-07 00:00:00,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,2015-06-07 00:00:00,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,2015-11-10 00:00:00,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [4]:
data.isnull

<bound method DataFrame.isnull of              id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee  minimum nights number of reviews          last review  \
0             $193            10.0               9.0           10/19/2021
1              $28            30.0              45.0            5/21/2022
2             $124             3.0               0.0                  NaN
3              $74            30.0             270.0  2019-05-07 00:00:00
4              $41            10.0               9.0           11/19/2018
...            ...             ...               ...                  ...
102594        $169             1.0               0.0                  NaN
102595        $167             1.0               1.0  2015-06-07 00:00:00
102596        $198             3.0               0.0                  NaN
102597        $109             2.0               5.0  2015-11-10 00:00:00
102598        $206             1.0               0.0                  NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]>

In [5]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [6]:
data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0.0,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0.0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1.0,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1.0,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,2019-05-07 00:00:00,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0.0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102325 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102191 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  float64
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     47756 non-null   object
 25  license                         2 non-null       object
dtypes: float64(10), int64(2), object(14)
memory usage: 20.4+ MB

In [8]:
data.describe()

,id,host id,lat,long,instant_bookable,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102494.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,0.497785,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,0.499998,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,0.000000,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,0.000000,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,0.000000,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,1.000000,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,1.000000,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [ ]:
data.isnull()